DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS cfg;
CREATE TABLE cfg (id SERIAL PRIMARY KEY, flagRunAddr VARCHAR(100), flnm VARCHAR(100));
CREATE TABLE users (id SERIAL PRIMARY KEY, lgn VARCHAR(100), psw VARCHAR(100), token VARCHAR(300), wtdh FLOAT DEFAULT 1000, balance FLOAT DEFAULT 10000);
CREATE TABLE orders (id SERIAL PRIMARY KEY, nmb VARCHAR(100), sts VARCHAR(100), token VARCHAR(300), accural FLOAT DEFAULT -1, ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP, sumbals FLOAT DEFAULT 0);